Custom 404 page implementation
json-schema-org/tour pull request #100
Opened 2024-10-26 09:26 UTC by AQIB-NAWAB

**What kind of change does this PR introduce?**
Developed a 404 page for better user experience 

**Issue Number:**
issue #99

**Screenshots/videos:**
Here is output of new custom 404 page 
![image](https://github.com/user-attachments/assets/42ed4fba-e280-42d0-96cc-02e03f5b2d0f)

http://localhost:3000/unknown-page

**Summary**

My main motivation to add 404 page was improving the better user experience

2024-10-26 11:17 UTC, DhairyaMajmudar commented
Thank you @AQIB-NAWAB for thoughtful PR can you pls. keep the designs matching the existing json schema color themes and componets

2024-10-29 16:42 UTC, AQIB-NAWAB commented
fix #99

2024-10-30 12:40 UTC, JeelRajodiya requested changes
Can you update the following
- Make sure the font size is as large as we have in the design 
- Fix alignment of the subtitle as per the design 
![image](https://github.com/user-attachments/assets/be3a4eb8-a581-4bd8-b535-b6adedd2ce19)
- make the borders rounded in the back to home button (as per the design)

2024-10-30 13:00 UTC, JeelRajodiya commented on app/not-found.tsx
> +    }, [colorMode]);
Do we need this useEffect?

2024-10-30 15:27 UTC, AQIB-NAWAB commented on app/not-found.tsx
> +    }, [colorMode]);
No actually we don't need this one

2024-10-30 15:28 UTC, AQIB-NAWAB commented
Here is update with figma values 
![image](https://github.com/user-attachments/assets/95bfa98d-da47-47c1-adc9-95fef86be452)
![image](https://github.com/user-attachments/assets/6c46679c-f161-4865-b490-e85f0e4db0b3)

2024-11-02 10:08 UTC, JeelRajodiya commented
Looks good to me!

2024-11-02 10:09 UTC, merged