Fix for ctrl+c on examples copies the whole text, not just the selection
json-schema-org/tour pull request #73
Opened 2024-09-13 17:41 UTC by AkshataABhat

Code fix for ctrl+c on examples copies the whole text, not just the selection 
Closes #53

2024-09-13 18:02 UTC, JeelRajodiya requested changes

2024-09-13 18:02 UTC, JeelRajodiya commented on app/components/CodeSnippet/CodeSnippet.tsx
> -  // remove the last \n from children
Why did we remove this comment? Please keep as it is.

2024-09-13 18:02 UTC, JeelRajodiya commented on package.json
> +    "my-app": "file:",
How is this change relevant?

2024-09-13 18:02 UTC, JeelRajodiya commented on app/components/CodeSnippet/CodeSnippet.tsx
> -    >
Yes, it works! but have you seen the pasted code after this change? The code is not formatted correctly. It looks something like the below image
![image](https://github.com/user-attachments/assets/b50f36be-d010-40eb-85ea-a1488149e1a0)


We also need to keep the code formatted as it is in the codeblock. This formatting issue is primarily from the [react-syntax-highlighter](https://github.com/react-syntax-highlighter/react-syntax-highlighter) library. You can look online and find out how other projects are using this library and find some solution for the issue.

2024-09-14 02:26 UTC, AkshataABhat commented
thank you for the review. will address these.

2024-09-14 02:28 UTC, closed without merging