fixes to ctrl+c issue on code snippet
json-schema-org/tour pull request #74
Opened 2024-09-15 15:58 UTC by AkshataABhat

2024-09-16 03:20 UTC, JeelRajodiya commented
**Great work** @AkshataABhat!  We have solve the problem, but I noticed one side effect of these changes. 
Some of the codeblocks have few lines highlighted in green, and since we are disabling the line wrapping. there will be no elements that wrap the lines, so the green highlights have disappeared. Can you please also resolve it?

![image](https://github.com/user-attachments/assets/69c75e82-ba63-4402-85fb-68a8a1bd5bf0)

2024-09-16 03:21 UTC, JeelRajodiya requested changes
**Great work** @AkshataABhat!  We have solve the problem, but I noticed one side effect of these changes. 
Some of the codeblocks have few lines highlighted in green, and since we are disabling the line wrapping. there will be no elements that wrap the lines, so the green highlights have disappeared. Can you please also resolve it?

![image](https://github.com/user-attachments/assets/69c75e82-ba63-4402-85fb-68a8a1bd5bf0)

2024-09-16 04:28 UTC, AkshataABhat commented
Yes, will do @JeelRajodiya 👍

2024-09-21 16:52 UTC, JeelRajodiya commented
Any updates @AkshataABhat?

2024-09-22 07:46 UTC, AkshataABhat commented
@JeelRajodiya pls check this pr.

2024-09-22 10:28 UTC, JeelRajodiya requested changes
Can you please ensure that these highlights have the full width (same as the codeblock) and does not have gaps between the lines? 

![Screenshot 2024-09-22 134033](https://github.com/user-attachments/assets/e9a406a9-12d7-4589-ab23-7e68a7cd4f27)

2024-09-22 12:01 UTC, AkshataABhat commented
Done, please check.

2024-09-22 12:44 UTC, JeelRajodiya requested changes

2024-09-22 12:44 UTC, JeelRajodiya commented on app/components/CodeSnippet/CodeSnippet.tsx
> +          whiteSpace: "pre-wrap",
please remove this style.
```suggestion
```

2024-09-22 12:44 UTC, JeelRajodiya commented on app/components/CodeSnippet/CodeSnippet.tsx
> +            width: "100%",
Please remove this style as well, the blocks seem to have 100% width by default. 
```suggestion
```

2024-09-22 12:46 UTC, JeelRajodiya commented on app/components/CodeSnippet/CodeSnippet.tsx
> +            width: "100%",
Please remove this style as well, the blocks seem to have 100% width by default.
```suggestion
```

2024-09-22 12:49 UTC, JeelRajodiya commented
Congrats Akshata! it works perfectly!

2024-09-22 12:50 UTC, merged