Solved Hydration Issue
json-schema-org/tour pull request #90
Opened 2024-10-05 05:12 UTC by RonakSurana-2001

Solved the turbopack issue #10 
Adding a video for verification purposes

https://github.com/user-attachments/assets/2f7c4e8e-698f-4212-96ce-c8f78458ad1d

2024-10-05 12:16 UTC, JeelRajodiya requested changes
Hello, While running the code I encountered these errors. 

![image](https://github.com/user-attachments/assets/7dbc7db5-5aae-47ef-8116-fd194a3e050c)
![image](https://github.com/user-attachments/assets/5133d3ea-71c9-4e5c-b109-a04034a29efd)

I also tried running the the same code in github codespaces (to ensure that these errors are not only specific to my machine) 
While testing, I found that on the first run the site does not throw any error, but when I close the server and restart it, these error appears. Please take a look
![image](https://github.com/user-attachments/assets/a6d60a57-cdd3-4c32-b558-736f976366d1)
![image](https://github.com/user-attachments/assets/ccf1b21b-83ed-4040-b0d0-d57477e20721)

2024-10-05 13:09 UTC, RonakSurana-2001 commented
Even I ran in github codespaces I not encountered any error.
See the video.

https://github.com/user-attachments/assets/17b6d331-f26e-43ef-bb1e-60ce79e1d7b0

2024-10-05 13:40 UTC, JeelRajodiya commented
I see, We are running different versions of next.js because of that we have different outcomes. 
Can you please upgrade the Next.js version on this PR? 
Follow this guide: https://nextjs.org/docs/app/building-your-application/upgrading/version-14

2024-10-05 14:03 UTC, RonakSurana-2001 commented
![image](https://github.com/user-attachments/assets/ce138a77-3cc6-4f29-b4a3-4d3b41cc12bf)

Next 14

2024-10-07 06:15 UTC, RonakSurana-2001 commented
Maintainers please reply

2024-10-07 09:17 UTC, JeelRajodiya commented
@RonakSurana-2001 
![image](https://github.com/user-attachments/assets/3e781dce-55b3-4aca-bb6d-d5fbb2ce1518)

Please check your package.json file, the next.js version is specified there. 
https://github.com/json-schema-org/tour/blob/a7678e360080a53d04592c635b3dbeab2c0cf4e9/package.json#L38

2024-10-07 09:22 UTC, JeelRajodiya requested changes

2024-10-07 09:22 UTC, JeelRajodiya commented on lib/server-functions.ts
Are these changes relevant to the issue? if yes please leave an explanation about what you did.

2024-10-07 09:22 UTC, JeelRajodiya commented on app/providers.tsx
Please leave an explanation about how this solves the issue? I suggest we avoid delayed rendering of the providers and their children, this can affect the server side build of the project and may cause performance issues.

2024-10-07 09:25 UTC, JeelRajodiya commented
> Even I ran in github codespaces I not encountered any error. Even when I ran multiple times. See the video.
> 
>  Media1.2.mp4

I see in your recording we have package-lock.json, which means you are installing packages using `npm install`. Instead of npm, please use `pnpm install` to install the packages, you can follow the guide form the [README.MD](https://github.com/json-schema-org/tour/blob/a7678e360080a53d04592c635b3dbeab2c0cf4e9/package.json#L38)

2024-12-21 15:32 UTC, JeelRajodiya commented
Closing this since no response from @RonakSurana-2001 and they have removed their issue assignment

2024-12-21 15:32 UTC, closed without merging