Updates the home page
json-schema-org/tour pull request #93
Opened 2024-10-06 16:43 UTC by pavanydg

**What kind of change does this PR introduce?**
enhances the home page.

**Issue Number:**

-  Closes #92 
-  Related to #72  
-  Others? 

**Screenshots/videos:**

[Screencast from 10-06-2024 10:11:02 PM.webm](https://github.com/user-attachments/assets/60540f39-2bc4-47b5-9176-2f0e636f2b08)

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

2024-10-06 17:28 UTC, pavanydg commented
@JeelRajodiya pl review.

2024-10-06 18:26 UTC, gregsdennis requested changes
As per my comments in the issue, the design of this page needs to match that of the home page: https://json-schema.org/.  This design does not match that.  Just glancing at it, I can tell the font doesn't even match.

We need to agree on a design before work is done.

2024-10-06 18:30 UTC, pavanydg commented
ok will update once the new design is finalized. Sorry for pulling a request without asking.

2024-10-06 18:33 UTC, gregsdennis commented
@pavanydg you had asked, and that's great.  But there was conversation on the issue that had not been resolved.  I don't want to you feel you broke some rule;  I just don't want you to feel like you wasted your time.  We discuss the change that needs to happen, then we implement the change.

2024-10-07 10:05 UTC, JeelRajodiya commented on app/components/HomePage/HomePage.tsx
It's Great, can you please use CSS grid of 4 rows each, this can make the links dynamic, incase we need to add more additional chapters we won't need to modify this component.

2024-10-07 10:09 UTC, pavanydg commented on app/components/HomePage/HomePage.tsx
Ok thanks I will do it once the design is finalized.

2024-10-07 19:40 UTC, pavanydg commented on app/components/HomePage/HomePage.tsx
hey i tried using grid, but the thing is it fills row wise. So the outcome will look like 
1.Getting Started             2.PrimitiveTypes 
and then from next line. So i have modified the previous code such that if we add additional chapters it works fine.

2024-10-08 02:50 UTC, JeelRajodiya commented on app/components/HomePage/HomePage.tsx
You can resolve the row wise filling issue using the [grid-auto-flow CSS property](https://developer.mozilla.org/en-US/docs/Web/CSS/grid-auto-flow)

2024-10-08 11:48 UTC, pavanydg commented on app/components/HomePage/HomePage.tsx
that property is not working as desired

2024-10-08 12:17 UTC, JeelRajodiya commented on app/components/HomePage/HomePage.tsx
it's okay

2024-10-08 12:50 UTC, pavanydg commented
@JeelRajodiya pl review.

2024-10-08 13:51 UTC, JeelRajodiya requested changes
It looks great on 80% zoom

![image](https://github.com/user-attachments/assets/ddaf055d-0867-40a4-b760-804032b627b2)


but when I zoom to 100% some of the links become difficult to read, please see the below screenshot

![image](https://github.com/user-attachments/assets/5983fb0e-3597-4dea-901a-00bdbc1aec86)

Can you please resolve it? (please consider testing with other zoom levels e.g. 110%, 120% etc. )

2024-10-09 04:02 UTC, pavanydg commented
@JeelRajodiya pl review.

2024-10-09 15:24 UTC, JeelRajodiya commented
It's perfect! Thank you for your contribution @pavanydg

2024-10-09 15:24 UTC, JeelRajodiya approved these changes

2024-10-09 16:47 UTC, merged