Save the code and a checkpoint so the users can start from where they left off
json-schema-org/tour pull request #97
Opened 2024-10-17 17:56 UTC by pavanydg

**What kind of change does this PR introduce?**

**Issue Number:**

-  Closes #68 
-  Related to #___ 
-  Others? 

**Screenshots/videos:**

[Screencast from 10-17-2024 11:25:16 PM.webm](https://github.com/user-attachments/assets/894007a3-f545-4d47-9ef7-034cff739e8a)

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

2024-10-18 04:23 UTC, pavanydg commented
@JeelRajodiya pl review

2024-10-21 05:38 UTC, JeelRajodiya commented
Hello, @pavanydg I am currently busy with my academics. I will review your PR after I get some time. Are you participating in hacktoberfest? Let me know so I can review the PR according to the   event timeline. Thanks.

2024-10-21 06:26 UTC, pavanydg commented
@JeelRajodiya it's fine.

2024-10-27 08:48 UTC, erosb commented on app/components/CodeEditor/CodeEditor.tsx
> +            setCodeString(codeString ? codeString : "")
Can we use `codeString ?? ""` here?

2024-10-27 08:48 UTC, erosb commented on lib/progressSaving.ts
> +  const key = `${chapter}.${lesson}`;
Please don't duplicate the key construction logic. I suggest extracting this to a `function codeStorageKey(chapter: number, lesson: number): string` function and using it in both  `getCode()` and `setCode()` and `resetCode()`.

2024-10-27 08:48 UTC, erosb commented on app/components/CodeEditor/CodeEditor.tsx
> +    setCode(chapterIndex, stepIndex, codeString);
It is hard to differentiate by these names what is the difference between `setCode()` and `setCodeString()` functions, because of the name similarity. I suggest renaming `setCode()` to `persistCode()` so that it better reflects what it does (puts the code into the persistence layer).

2024-10-27 08:48 UTC, erosb commented on lib/progressSaving.ts
> +export function getcheckPoint(){
Please make the naming consistent ( `getcheckPoint()` -> `getCheckPoint()`)

2024-10-27 08:48 UTC, erosb commented on lib/progressSaving.ts
> +  if (typeof window === "undefined") return false;
Why do we need it? Will this code ever run in non-browser environment?

2024-10-27 08:48 UTC, erosb commented on lib/progressSaving.ts
> +  if (typeof window === "undefined") return false;
The return value of this function is never used, so I suggest either just make it a `return ;` or extract this whole logic into one function (but I'd question if it is even necessary - see my other question about it).

2024-10-27 08:48 UTC, erosb commented on app/page.tsx
> +      <CheckpointRedirect/>
Does the redirection need to be implemented as a component? Since it isn't visual, I suggest just calling before the `return` expression as a plain function. No need to wrap it into a component.

2024-10-27 08:48 UTC, erosb commented on app/components/NavBarMenus/NavBarMenus.tsx
> +                  window.location.reload()
Is it necessary to reload here?

2024-10-27 08:48 UTC, erosb commented on app/components/NavBarMenus/NavBarMenus.tsx
> +                  localStorage.removeItem("codeData")
I think it would be better to separate all `localStorage` usage into `progressSaving.ts` . The component doesn't need to be aware of how the persistence layer of the app is implemented.

2024-10-28 06:18 UTC, JeelRajodiya requested changes

2024-10-28 06:18 UTC, JeelRajodiya commented on app/components/HomePage/HomePage.tsx
Can you please remove these changes? These changes are from your previous PR (homepage redesign).

2024-10-28 06:20 UTC, JeelRajodiya commented
@erosb Thanks for the review.
@pavanydg Please make changes suggested by @erosb, and avoid including commits from your prior PR.

2024-10-28 07:06 UTC, pavanydg commented
@JeelRajodiya will do it.

2024-10-28 16:59 UTC, pavanydg commented on lib/progressSaving.ts
> +  if (typeof window === "undefined") return false;
yeah i am using it to get the saved code from localstorage, if a user has already written any code for a lesson.

2024-10-28 16:59 UTC, pavanydg commented on app/components/CodeEditor/CodeEditor.tsx
> +            setCodeString(codeString ? codeString : "")
Acutally i don't know about codestring and setCodeString yet. I have not worked on it. It has been used from other component.

2024-10-28 17:02 UTC, erosb commented on lib/progressSaving.ts
> +  if (typeof window === "undefined") return false;
The question was about the `if (typeof window === "undefined") return false;` line :)

2024-10-28 17:02 UTC, pavanydg commented on app/page.tsx
> +      <CheckpointRedirect/>
Its using useEffect hook, so if i put it home page i have to make it a client component. What should i do?

2024-10-28 17:02 UTC, pavanydg commented on app/components/NavBarMenus/NavBarMenus.tsx
> +                  window.location.reload()
the changes of the reset code button is not visible immediately. So i put a reload.

2024-10-28 17:04 UTC, pavanydg commented on lib/progressSaving.ts
> +  if (typeof window === "undefined") return false;
Oops I will remove it.

2024-10-28 17:16 UTC, pavanydg commented
@JeelRajodiya done with the changes should i make a new pr?

2024-10-28 17:44 UTC, erosb commented on app/components/NavBarMenus/NavBarMenus.tsx
> +                  window.location.reload()
Can we solve this problem in an other way? Full page reload is not good UX. @JeelRajodiya  can you please advise here?

2024-10-28 18:52 UTC, JeelRajodiya commented
**Force push** all the changes on this PR (while only including the important commits). If you create a new PR all the reviews will be lost, so I suggest to avoid that.

2024-10-29 10:21 UTC, JeelRajodiya commented on app/components/NavBarMenus/NavBarMenus.tsx
> +                  window.location.reload()
I am waiting for @pavanydg to remove the old commits, so that I can test it locally on my machine and advise accordingly.

2024-10-29 12:19 UTC, closed without merging

2024-10-29 14:09 UTC, pavanydg commented
@JeelRajodiya @erosb sorry this pr got close by mistake. please go through this pr #102